apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: newsman
          artifact-id: ec1e7baf-c3e7-4e86-abc8-f9b538781953
          target-environment: mm-qa-aspm