apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: newsman
          artifact-id: 8b9b70b3-bc16-4437-8aed-cc8092933d88
          target-environment: mm-qa-aspm